/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTenantsRouteImport } from './routes/_app.tenants'
import { Route as AppPropertiesRouteImport } from './routes/_app.properties'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppLeasesRouteImport } from './routes/_app.leases'
import { Route as AppTenantsIdRouteImport } from './routes/_app.tenants.$id'
import { Route as AppPropertiesIdRouteImport } from './routes/_app.properties.$id'
import { Route as AppLeasesIdRouteImport } from './routes/_app.leases.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsRoute = AppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesRoute = AppPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppLeasesRoute = AppLeasesRouteImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsIdRoute = AppTenantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTenantsRoute,
} as any)
const AppPropertiesIdRoute = AppPropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPropertiesRoute,
} as any)
const AppLeasesIdRoute = AppLeasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLeasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/leases': typeof AppLeasesRouteWithChildren
  '/payments': typeof AppPaymentsRoute
  '/properties': typeof AppPropertiesRouteWithChildren
  '/tenants': typeof AppTenantsRouteWithChildren
  '/leases/$id': typeof AppLeasesIdRoute
  '/properties/$id': typeof AppPropertiesIdRoute
  '/tenants/$id': typeof AppTenantsIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/leases': typeof AppLeasesRouteWithChildren
  '/payments': typeof AppPaymentsRoute
  '/properties': typeof AppPropertiesRouteWithChildren
  '/tenants': typeof AppTenantsRouteWithChildren
  '/': typeof AppIndexRoute
  '/leases/$id': typeof AppLeasesIdRoute
  '/properties/$id': typeof AppPropertiesIdRoute
  '/tenants/$id': typeof AppTenantsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/leases': typeof AppLeasesRouteWithChildren
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/properties': typeof AppPropertiesRouteWithChildren
  '/_app/tenants': typeof AppTenantsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/leases/$id': typeof AppLeasesIdRoute
  '/_app/properties/$id': typeof AppPropertiesIdRoute
  '/_app/tenants/$id': typeof AppTenantsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/leases'
    | '/payments'
    | '/properties'
    | '/tenants'
    | '/leases/$id'
    | '/properties/$id'
    | '/tenants/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/leases'
    | '/payments'
    | '/properties'
    | '/tenants'
    | '/'
    | '/leases/$id'
    | '/properties/$id'
    | '/tenants/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/_app/leases'
    | '/_app/payments'
    | '/_app/properties'
    | '/_app/tenants'
    | '/_app/'
    | '/_app/leases/$id'
    | '/_app/properties/$id'
    | '/_app/tenants/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenants': {
      id: '/_app/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AppTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/properties': {
      id: '/_app/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AppPropertiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leases': {
      id: '/_app/leases'
      path: '/leases'
      fullPath: '/leases'
      preLoaderRoute: typeof AppLeasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenants/$id': {
      id: '/_app/tenants/$id'
      path: '/$id'
      fullPath: '/tenants/$id'
      preLoaderRoute: typeof AppTenantsIdRouteImport
      parentRoute: typeof AppTenantsRoute
    }
    '/_app/properties/$id': {
      id: '/_app/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof AppPropertiesIdRouteImport
      parentRoute: typeof AppPropertiesRoute
    }
    '/_app/leases/$id': {
      id: '/_app/leases/$id'
      path: '/$id'
      fullPath: '/leases/$id'
      preLoaderRoute: typeof AppLeasesIdRouteImport
      parentRoute: typeof AppLeasesRoute
    }
  }
}

interface AppLeasesRouteChildren {
  AppLeasesIdRoute: typeof AppLeasesIdRoute
}

const AppLeasesRouteChildren: AppLeasesRouteChildren = {
  AppLeasesIdRoute: AppLeasesIdRoute,
}

const AppLeasesRouteWithChildren = AppLeasesRoute._addFileChildren(
  AppLeasesRouteChildren,
)

interface AppPropertiesRouteChildren {
  AppPropertiesIdRoute: typeof AppPropertiesIdRoute
}

const AppPropertiesRouteChildren: AppPropertiesRouteChildren = {
  AppPropertiesIdRoute: AppPropertiesIdRoute,
}

const AppPropertiesRouteWithChildren = AppPropertiesRoute._addFileChildren(
  AppPropertiesRouteChildren,
)

interface AppTenantsRouteChildren {
  AppTenantsIdRoute: typeof AppTenantsIdRoute
}

const AppTenantsRouteChildren: AppTenantsRouteChildren = {
  AppTenantsIdRoute: AppTenantsIdRoute,
}

const AppTenantsRouteWithChildren = AppTenantsRoute._addFileChildren(
  AppTenantsRouteChildren,
)

interface AppRouteChildren {
  AppLeasesRoute: typeof AppLeasesRouteWithChildren
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPropertiesRoute: typeof AppPropertiesRouteWithChildren
  AppTenantsRoute: typeof AppTenantsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLeasesRoute: AppLeasesRouteWithChildren,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPropertiesRoute: AppPropertiesRouteWithChildren,
  AppTenantsRoute: AppTenantsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
