/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OwnerRouteImport } from './routes/_owner'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantLoginRouteImport } from './routes/tenant/login'
import { Route as TenantTenantRouteImport } from './routes/tenant/_tenant'
import { Route as OwnerTenantsRouteImport } from './routes/_owner.tenants'
import { Route as OwnerPropertiesRouteImport } from './routes/_owner.properties'
import { Route as OwnerPaymentsRouteImport } from './routes/_owner.payments'
import { Route as OwnerLeasesRouteImport } from './routes/_owner.leases'
import { Route as OwnerDashboardRouteImport } from './routes/_owner.dashboard'
import { Route as TenantTenantIndexRouteImport } from './routes/tenant/_tenant.index'
import { Route as TenantTenantPropertiesRouteImport } from './routes/tenant/_tenant.properties'
import { Route as TenantTenantProfileRouteImport } from './routes/tenant/_tenant.profile'
import { Route as TenantTenantPaymentsRouteImport } from './routes/tenant/_tenant.payments'
import { Route as TenantTenantLeasesRouteImport } from './routes/tenant/_tenant.leases'
import { Route as OwnerTenantsIdRouteImport } from './routes/_owner.tenants.$id'
import { Route as OwnerPropertiesIdRouteImport } from './routes/_owner.properties.$id'
import { Route as OwnerLeasesIdRouteImport } from './routes/_owner.leases.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/_owner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantLoginRoute = TenantLoginRouteImport.update({
  id: '/tenant/login',
  path: '/tenant/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantTenantRoute = TenantTenantRouteImport.update({
  id: '/tenant/_tenant',
  path: '/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerTenantsRoute = OwnerTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPropertiesRoute = OwnerPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPaymentsRoute = OwnerPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerLeasesRoute = OwnerLeasesRouteImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OwnerRoute,
} as any)
const TenantTenantIndexRoute = TenantTenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantTenantRoute,
} as any)
const TenantTenantPropertiesRoute = TenantTenantPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => TenantTenantRoute,
} as any)
const TenantTenantProfileRoute = TenantTenantProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TenantTenantRoute,
} as any)
const TenantTenantPaymentsRoute = TenantTenantPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => TenantTenantRoute,
} as any)
const TenantTenantLeasesRoute = TenantTenantLeasesRouteImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => TenantTenantRoute,
} as any)
const OwnerTenantsIdRoute = OwnerTenantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OwnerTenantsRoute,
} as any)
const OwnerPropertiesIdRoute = OwnerPropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OwnerPropertiesRoute,
} as any)
const OwnerLeasesIdRoute = OwnerLeasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OwnerLeasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof OwnerDashboardRoute
  '/leases': typeof OwnerLeasesRouteWithChildren
  '/payments': typeof OwnerPaymentsRoute
  '/properties': typeof OwnerPropertiesRouteWithChildren
  '/tenants': typeof OwnerTenantsRouteWithChildren
  '/tenant': typeof TenantTenantRouteWithChildren
  '/tenant/login': typeof TenantLoginRoute
  '/leases/$id': typeof OwnerLeasesIdRoute
  '/properties/$id': typeof OwnerPropertiesIdRoute
  '/tenants/$id': typeof OwnerTenantsIdRoute
  '/tenant/leases': typeof TenantTenantLeasesRoute
  '/tenant/payments': typeof TenantTenantPaymentsRoute
  '/tenant/profile': typeof TenantTenantProfileRoute
  '/tenant/properties': typeof TenantTenantPropertiesRoute
  '/tenant/': typeof TenantTenantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof OwnerDashboardRoute
  '/leases': typeof OwnerLeasesRouteWithChildren
  '/payments': typeof OwnerPaymentsRoute
  '/properties': typeof OwnerPropertiesRouteWithChildren
  '/tenants': typeof OwnerTenantsRouteWithChildren
  '/tenant/login': typeof TenantLoginRoute
  '/leases/$id': typeof OwnerLeasesIdRoute
  '/properties/$id': typeof OwnerPropertiesIdRoute
  '/tenants/$id': typeof OwnerTenantsIdRoute
  '/tenant/leases': typeof TenantTenantLeasesRoute
  '/tenant/payments': typeof TenantTenantPaymentsRoute
  '/tenant/profile': typeof TenantTenantProfileRoute
  '/tenant/properties': typeof TenantTenantPropertiesRoute
  '/tenant': typeof TenantTenantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_owner': typeof OwnerRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_owner/dashboard': typeof OwnerDashboardRoute
  '/_owner/leases': typeof OwnerLeasesRouteWithChildren
  '/_owner/payments': typeof OwnerPaymentsRoute
  '/_owner/properties': typeof OwnerPropertiesRouteWithChildren
  '/_owner/tenants': typeof OwnerTenantsRouteWithChildren
  '/tenant/_tenant': typeof TenantTenantRouteWithChildren
  '/tenant/login': typeof TenantLoginRoute
  '/_owner/leases/$id': typeof OwnerLeasesIdRoute
  '/_owner/properties/$id': typeof OwnerPropertiesIdRoute
  '/_owner/tenants/$id': typeof OwnerTenantsIdRoute
  '/tenant/_tenant/leases': typeof TenantTenantLeasesRoute
  '/tenant/_tenant/payments': typeof TenantTenantPaymentsRoute
  '/tenant/_tenant/profile': typeof TenantTenantProfileRoute
  '/tenant/_tenant/properties': typeof TenantTenantPropertiesRoute
  '/tenant/_tenant/': typeof TenantTenantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/leases'
    | '/payments'
    | '/properties'
    | '/tenants'
    | '/tenant'
    | '/tenant/login'
    | '/leases/$id'
    | '/properties/$id'
    | '/tenants/$id'
    | '/tenant/leases'
    | '/tenant/payments'
    | '/tenant/profile'
    | '/tenant/properties'
    | '/tenant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/leases'
    | '/payments'
    | '/properties'
    | '/tenants'
    | '/tenant/login'
    | '/leases/$id'
    | '/properties/$id'
    | '/tenants/$id'
    | '/tenant/leases'
    | '/tenant/payments'
    | '/tenant/profile'
    | '/tenant/properties'
    | '/tenant'
  id:
    | '__root__'
    | '/'
    | '/_owner'
    | '/login'
    | '/register'
    | '/_owner/dashboard'
    | '/_owner/leases'
    | '/_owner/payments'
    | '/_owner/properties'
    | '/_owner/tenants'
    | '/tenant/_tenant'
    | '/tenant/login'
    | '/_owner/leases/$id'
    | '/_owner/properties/$id'
    | '/_owner/tenants/$id'
    | '/tenant/_tenant/leases'
    | '/tenant/_tenant/payments'
    | '/tenant/_tenant/profile'
    | '/tenant/_tenant/properties'
    | '/tenant/_tenant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TenantTenantRoute: typeof TenantTenantRouteWithChildren
  TenantLoginRoute: typeof TenantLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_owner': {
      id: '/_owner'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/login': {
      id: '/tenant/login'
      path: '/tenant/login'
      fullPath: '/tenant/login'
      preLoaderRoute: typeof TenantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/_tenant': {
      id: '/tenant/_tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof TenantTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_owner/tenants': {
      id: '/_owner/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof OwnerTenantsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/properties': {
      id: '/_owner/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof OwnerPropertiesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/payments': {
      id: '/_owner/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof OwnerPaymentsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/leases': {
      id: '/_owner/leases'
      path: '/leases'
      fullPath: '/leases'
      preLoaderRoute: typeof OwnerLeasesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/dashboard': {
      id: '/_owner/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/tenant/_tenant/': {
      id: '/tenant/_tenant/'
      path: '/'
      fullPath: '/tenant/'
      preLoaderRoute: typeof TenantTenantIndexRouteImport
      parentRoute: typeof TenantTenantRoute
    }
    '/tenant/_tenant/properties': {
      id: '/tenant/_tenant/properties'
      path: '/properties'
      fullPath: '/tenant/properties'
      preLoaderRoute: typeof TenantTenantPropertiesRouteImport
      parentRoute: typeof TenantTenantRoute
    }
    '/tenant/_tenant/profile': {
      id: '/tenant/_tenant/profile'
      path: '/profile'
      fullPath: '/tenant/profile'
      preLoaderRoute: typeof TenantTenantProfileRouteImport
      parentRoute: typeof TenantTenantRoute
    }
    '/tenant/_tenant/payments': {
      id: '/tenant/_tenant/payments'
      path: '/payments'
      fullPath: '/tenant/payments'
      preLoaderRoute: typeof TenantTenantPaymentsRouteImport
      parentRoute: typeof TenantTenantRoute
    }
    '/tenant/_tenant/leases': {
      id: '/tenant/_tenant/leases'
      path: '/leases'
      fullPath: '/tenant/leases'
      preLoaderRoute: typeof TenantTenantLeasesRouteImport
      parentRoute: typeof TenantTenantRoute
    }
    '/_owner/tenants/$id': {
      id: '/_owner/tenants/$id'
      path: '/$id'
      fullPath: '/tenants/$id'
      preLoaderRoute: typeof OwnerTenantsIdRouteImport
      parentRoute: typeof OwnerTenantsRoute
    }
    '/_owner/properties/$id': {
      id: '/_owner/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof OwnerPropertiesIdRouteImport
      parentRoute: typeof OwnerPropertiesRoute
    }
    '/_owner/leases/$id': {
      id: '/_owner/leases/$id'
      path: '/$id'
      fullPath: '/leases/$id'
      preLoaderRoute: typeof OwnerLeasesIdRouteImport
      parentRoute: typeof OwnerLeasesRoute
    }
  }
}

interface OwnerLeasesRouteChildren {
  OwnerLeasesIdRoute: typeof OwnerLeasesIdRoute
}

const OwnerLeasesRouteChildren: OwnerLeasesRouteChildren = {
  OwnerLeasesIdRoute: OwnerLeasesIdRoute,
}

const OwnerLeasesRouteWithChildren = OwnerLeasesRoute._addFileChildren(
  OwnerLeasesRouteChildren,
)

interface OwnerPropertiesRouteChildren {
  OwnerPropertiesIdRoute: typeof OwnerPropertiesIdRoute
}

const OwnerPropertiesRouteChildren: OwnerPropertiesRouteChildren = {
  OwnerPropertiesIdRoute: OwnerPropertiesIdRoute,
}

const OwnerPropertiesRouteWithChildren = OwnerPropertiesRoute._addFileChildren(
  OwnerPropertiesRouteChildren,
)

interface OwnerTenantsRouteChildren {
  OwnerTenantsIdRoute: typeof OwnerTenantsIdRoute
}

const OwnerTenantsRouteChildren: OwnerTenantsRouteChildren = {
  OwnerTenantsIdRoute: OwnerTenantsIdRoute,
}

const OwnerTenantsRouteWithChildren = OwnerTenantsRoute._addFileChildren(
  OwnerTenantsRouteChildren,
)

interface OwnerRouteChildren {
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  OwnerLeasesRoute: typeof OwnerLeasesRouteWithChildren
  OwnerPaymentsRoute: typeof OwnerPaymentsRoute
  OwnerPropertiesRoute: typeof OwnerPropertiesRouteWithChildren
  OwnerTenantsRoute: typeof OwnerTenantsRouteWithChildren
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerDashboardRoute: OwnerDashboardRoute,
  OwnerLeasesRoute: OwnerLeasesRouteWithChildren,
  OwnerPaymentsRoute: OwnerPaymentsRoute,
  OwnerPropertiesRoute: OwnerPropertiesRouteWithChildren,
  OwnerTenantsRoute: OwnerTenantsRouteWithChildren,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface TenantTenantRouteChildren {
  TenantTenantLeasesRoute: typeof TenantTenantLeasesRoute
  TenantTenantPaymentsRoute: typeof TenantTenantPaymentsRoute
  TenantTenantProfileRoute: typeof TenantTenantProfileRoute
  TenantTenantPropertiesRoute: typeof TenantTenantPropertiesRoute
  TenantTenantIndexRoute: typeof TenantTenantIndexRoute
}

const TenantTenantRouteChildren: TenantTenantRouteChildren = {
  TenantTenantLeasesRoute: TenantTenantLeasesRoute,
  TenantTenantPaymentsRoute: TenantTenantPaymentsRoute,
  TenantTenantProfileRoute: TenantTenantProfileRoute,
  TenantTenantPropertiesRoute: TenantTenantPropertiesRoute,
  TenantTenantIndexRoute: TenantTenantIndexRoute,
}

const TenantTenantRouteWithChildren = TenantTenantRoute._addFileChildren(
  TenantTenantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwnerRoute: OwnerRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TenantTenantRoute: TenantTenantRouteWithChildren,
  TenantLoginRoute: TenantLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
